version: "3"
services: 
    app:
        #container_name: my_project
        #image: 535794100467.dkr.ecr.us-east-2.amazonaws.com/userdetails_docker
        build:
            context: . #use the current folder
            dockerfile: dockerfile #Name of the docker file
        restart: always
        volumes:
            - ./src:/usr/src/app/src
        build: .
        ports:
            - "8080:8000"
        links:
            - mongo
    mongo:
        container_name: mongoDB
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27018:27017"